server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5332/customer
        username: amigoscode
        password: password
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
    main:
        web-application-type: none

# connect to db container via terminal: docker exec -it postgres bash (allows for execution of shell commands in postgres container)
# connect to db container: /# psql -U amigoscode
# list databases: /l
# create customer database: CREATE DATABASE customer; (\l displays customer in database list)
# cntrl d exists database list and container